apiVersion: v1
kind: Service
metadata:
  name: prom-example
  namespace: default
  labels:
    app: prom-example
spec:
  selector:
    app: prom-example
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
