apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-example-monitor
  labels:
    release: prometheus-stack  # must match your helm release name
spec:
  selector:
    matchLabels:
      app: prom-example
  endpoints:
  - port: 8080
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
      - default
