apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-example-monitor
  labels:
    release: prometheus-stack  # must match Helm release name
spec:
  selector:
    matchLabels:
      app: prom-example
  endpoints:
  - port: "8080"         # fixed: string instead of integer
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
      - default
