# prometheus-example-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-example
  labels:
    app: prom-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-example
  template:
    metadata:
      labels:
        app: prom-example
    spec:
      containers:
      - name: prom-example
        image: quay.io/brancz/prometheus-example-app:v0.3.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: prom-example
  labels:
    app: prom-example
spec:
  selector:
    app: prom-example
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
